/source/switch GuidantGalileo

/run/initialize
/control/verbose 1
/run/verbose 1
/tracking/verbose 0


#Visualisation starts
/vis/open HepRepFile

#Auxillaryedge shows the edge as the simulator sees it, which is not ideal (composed of triangles)

/vis/viewer/set/auxiliaryEdge false
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/vis/scene/create
/vis/sceneHandler/attach
/vis/scene/add/volume world

/vis/scene/add/trajectories rich
/vis/viewer/flush

#Particle Filter
 #Implemented this so that we don't see neutrinos
 /vis/filtering/trajectories/create/particleFilter 
 /vis/filtering/trajectories/particleFilter-0/add e-
 /vis/filtering/trajectories/particleFilter-0/add gamma
 #/vis/filtering/trajectories/particleFilter-0/invert true

#Initial Volume Filter
 #/vis/filtering/trajectories/create/originVolumeFilter
 #/vis/filtering/trajectories/originVolumeFilter-0/add CapsuleCylinder_phys
 #/vis/filtering/trajectories/originVolumeFilter-0/add CapsuleCylinder_physend1
 #/vis/filtering/trajectories/originVolumeFilter-0/add CapsuleCylinder_physend2

#Draw by Charge
 /vis/modeling/trajectories/create/drawByCharge
 /vis/modeling/trajectories/drawByCharge-0/set 1 blue
 /vis/modeling/trajectories/drawByCharge-0/set -1 red
 /vis/modeling/trajectories/drawByCharge-0/setRGBA 0 0 1 0 0
 /vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 4


/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
# Visualisation ends

#16 Sources of Tm-170 Along the source train

/gps/source/intensity 1
/gps/particle ion
/gps/ion 15 32 0 0
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 0.24 mm
/gps/pos/halfz 10 mm
/gps/energy 0 keV
/gps/pos/centre 0 0 0 mm

/run/beamOn 10
